/**
 * Shared data contract for Camels Physio.
 *
 * Every collection is a Record<id, record>. Every mergeable record carries
 * `updatedAt` (ISO UTC string) + `updatedBy` so that phones exchanging JSON
 * backups converge with a "newest edit wins" rule. Deletions are tombstones
 * (a flag flipped and `updatedAt` bumped) so a deletion beats a stale live copy.
 */

export const USER_IDS = ['shahar', 'maya', 'neta'] as const
export type UserId = (typeof USER_IDS)[number]

/** Local calendar date, 'YYYY-MM-DD'. Never derived from toISOString(). */
export type DateKey = string
/** 'YYYY-MM' */
export type MonthKey = string
/** ISO 8601 UTC timestamp from new Date().toISOString(); compared as strings. */
export type Stamp = string

export interface Meta {
  updatedAt: Stamp
  updatedBy: UserId
}

// ---------------------------------------------------------------- players
export const BODY_TYPES = ['Athletic', 'Flexible', 'Strong', 'Compact'] as const
export type BodyType = (typeof BODY_TYPES)[number] | ''

export interface Player extends Meta {
  id: string
  name: string
  number: number | null
  fitnessLevel: string
  bodyStructure: string
  bodyType: BodyType
  pastInjuries: string
  rom: string
  strengthening: string
  /** Seeded players are restored if missing and cannot be deleted. */
  seeded: boolean
  /** Tombstone (manually added players only). */
  deleted: boolean
}

export type PlayerFields = Pick<
  Player,
  'name' | 'number' | 'fitnessLevel' | 'bodyStructure' | 'bodyType' | 'pastInjuries' | 'rom' | 'strengthening'
>

// ------------------------------------------------------------ team events
export const TEAM_EVENT_KINDS = ['none', 'training', 'game'] as const
/** 'none' is the tombstone: the manager cleared the event. */
export type TeamEventKind = (typeof TEAM_EVENT_KINDS)[number]

export interface TeamEvent extends Meta {
  /** id === date */
  id: DateKey
  date: DateKey
  kind: TeamEventKind
}

// -------------------------------------------------------------- work days
export interface WorkDay extends Meta {
  /** `${userId}_${date}` */
  id: string
  userId: UserId
  date: DateKey
  /** false is the tombstone: the user un-marked the day. */
  worked: boolean
}

// --------------------------------------------------------------- sessions
export const ATTENDANCE_STATUSES = ['unset', 'present', 'absent', 'injured'] as const
/** 'unset' is the tombstone for a cleared attendance mark. */
export type AttendanceStatus = (typeof ATTENDANCE_STATUSES)[number]

export interface PlayerAttendance extends Meta {
  status: AttendanceStatus
}

export const SESSION_TYPES = ['workday', 'training', 'game'] as const
export type SessionType = (typeof SESSION_TYPES)[number]

/**
 * One session per calendar date (id `s-${date}`), generated by
 * "Apply Monthly Attendance". There is deliberately NO session-level
 * updatedAt: notes and each attendance entry merge independently, `physios`
 * is a set-union, and `type` is re-derived from the calendar after a merge.
 */
export interface Session {
  id: string
  date: DateKey
  type: SessionType
  physios: UserId[]
  notes: Meta & { text: string }
  playerAttendance: Record<string, PlayerAttendance>
  createdAt: Stamp
  createdBy: UserId
}

// --------------------------------------------------------------- injuries
export const BODY_PARTS = [
  'Shoulder',
  'Elbow',
  'Wrist/Hand',
  'Finger',
  'Back',
  'Hip/Groin',
  'Hamstring',
  'Quad',
  'Knee',
  'Ankle',
  'Foot',
  'Head',
  'Other',
] as const
export type BodyPart = (typeof BODY_PARTS)[number]

export const SIDES = ['left', 'right', 'both'] as const
export type Side = (typeof SIDES)[number] | null

export const SEVERITIES = ['Low', 'Medium', 'High'] as const
export type Severity = (typeof SEVERITIES)[number]

export const INJURY_STATUSES = ['Active', 'Recovered'] as const
export type InjuryStatus = (typeof INJURY_STATUSES)[number]

export interface Injury extends Meta {
  /** `i-${uuid}` */
  id: string
  playerId: string
  /** Session the injury was reported in; null for injuries added from the profile. */
  sessionId: string | null
  date: DateKey
  bodyPart: BodyPart
  side: Side
  severity: Severity
  status: InjuryStatus
  description: string
  reportedBy: UserId
  /** Tombstone. */
  deleted: boolean
}

export type InjuryFields = Pick<Injury, 'bodyPart' | 'side' | 'severity' | 'status' | 'description' | 'date'>

export interface NewInjuryInput {
  playerId: string
  sessionId: string | null
  date: DateKey
  bodyPart: BodyPart
  side: Side
  severity: Severity
  status: InjuryStatus
  description: string
}

// ------------------------------------------------------- persisted state
export const SCHEMA_VERSION = 1 as const

/** Everything that is exported/imported. Device-only state (currentUserId) is NOT part of it. */
export interface PersistedState {
  schemaVersion: typeof SCHEMA_VERSION
  players: Record<string, Player>
  teamEvents: Record<DateKey, TeamEvent>
  workDays: Record<string, WorkDay>
  sessions: Record<string, Session>
  injuries: Record<string, Injury>
}

export function emptyPersistedState(): PersistedState {
  return { schemaVersion: SCHEMA_VERSION, players: {}, teamEvents: {}, workDays: {}, sessions: {}, injuries: {} }
}

// ---------------------------------------------------------------- backup
export const BACKUP_APP_ID = 'camels-physio' as const

export interface BackupEnvelope {
  app: typeof BACKUP_APP_ID
  schemaVersion: number
  exportedAt: Stamp
  exportedBy: UserId | null
  data: PersistedState
}

export type ParseResult =
  | { ok: true; envelope: BackupEnvelope; skipped: number }
  | { ok: false; error: string }

// ----------------------------------------------------------------- merge
export type ConflictPolicy = 'newest' | 'local'

export interface Counts {
  added: number
  updated: number
  unchanged: number
}

export interface MergeSummary {
  players: Counts
  teamEvents: Counts
  workDays: Counts
  sessions: Counts
  attendanceEntries: Counts
  injuries: Counts
  skippedInvalid: number
}

// ----------------------------------------------------------------- apply
export interface ApplyResult {
  /** sessions newly created */
  created: number
  /** sessions that already existed and had type/physios refreshed */
  updated: number
  /** sessions that already existed and needed no change */
  unchanged: number
  /** empty sessions removed because their date is no longer on the calendar */
  pruned: number
}

// ----------------------------------------------------------------- misc
export const CALENDAR_MODES = ['team', 'me'] as const
export type CalendarMode = (typeof CALENDAR_MODES)[number]
